# 配置服务
service:
  ## 认证服务
  auth-service:
    name: auth-application
    url: http://localhost:6000
  ## 用户服务
  user-service:
    name: user-application
    url: http://localhost:8000
  ## 消息服务
  message-service:
    name: message-application
    url: http://localhost:7000


# 配置路由服务
## 用户服务
spring:
  cloud:
    gateway:
      routes:
        - id: ${service.auth-service.name}
          uri: ${service.auth-service.url}
          predicates:
            - Path=/auth/**
        - id: ${service.user-service.name}
          uri: ${service.user-service.url}
          predicates:
            - Path=/user/**
        - id: ${service.message-service.name}
          uri: ${service.message-service.url}
          predicates:
            - Path=/message/**